language: node_js
node_js:
  - 'node'

notifications:
  email: false

addons:
  apt:
    packages:
      - zip
      - unzip

before_cache:
  - rm -rf node_modules/.cache

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - yarn build
  - node ./build/locales/locales.js

after_success:
  - zip -rq dist.zip dist
  - res=$(curl -F "file=@dist.zip" https://file.io/?expires=3d)
  - echo $res
  - bash ./build/deploy-www.sh

before_deploy:
  - openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv -in ./build/encrypt.zip.enc -out ./encrypt.zip -d
  - unzip encrypt.zip

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./build/deploy.sh
  on:
    tags: true

env:
  global:
    # GitHub Token (for docs)
    - secure: CWCrVum9h0996SkQgzGourEYisqdVw/PEl36Ue6D7gdsPGZgOhCzJCJkKH5Uk3fkNF4GXHA0u+8eOJGyMiHXWH1D10+fgYDUSuEEE8/kaUhAvDXymQwJim+tax1johoa5WyitjyWxCXFtfHBcBC6uDI02jkEhhiSUASsXetEFi9I9z4KI2zDLQk8s+y2PKGinusnFGcY1eSKISeDNYP3AZbaieVpgFsiVK+uTLxlmN+l2j7MfnOTZ05VAEQBRGpe0jB9aTm2nSPmXWHvVOb60RhrpI+U2xRGTej+VvoKjIYgz2oSdtC+SQQAtuBAeX+jdpkrK3/Y18n9qCDOjlHZv2RohQEcHzyIOcErF/bwW6ZqYNFOogB2svoiSNCrKPJLCTdl9L0dro+vLSUBxt6F10sTANswe8j9sNVOr9kfsamJRAGDlHItyGA5qC44miO+3ZQyEAXNLJHMctilSrmy3wZqUAOVXl6azJlZrzNt+XVZCrq5FMr+3Fc+p+RhoSheKJi2G8ICFDqqAqOgVxW6nV+3V6yG1arTqX8ArV2wHziFArwotIqdZwWnwdFCfn5kAZpoRefRx45zbj1qJEBO8ByZvwYq3LHr3tsFDenyriMXaNidqMfJlDtAKoyVKdDi/7oWSpzzvupX2ThxVeQF68IJ6v+9Y2U7SUo9LtdRFFk=
    # Transifex Token
    - secure: VtVRiZQIiVVsvVpoMAvYjFyr9ZeDWppMw0FZGeCKAcXdrJxaqe7XuQVPDcWZv1UQq4Gq1B2CbfBMPXrH19iaQ62Dcz+vvbg5euc4Ioix5tul7uawE0pOQdFcopua9BQxwGOyziiVvBXPjTMXEzzyKIRmW/Fg7/eUbVmBcSFVIz0SF284ILG1ocDK3mzpGBWkXalsF/3jmhqnAlWSjMciG4WV5/7QfsaX6AAeUOVFJoIwBmS5/wLbXEOIhQVZxtV3lsHt5B8x3ApNOQHf6PcbeqBdW/ZNH9mXPvJ+R8LtSnylt4JTcSuehhRiTc7RowmXoPjCDEjod1ngmRq/WfRHXqfE1oaQJt8fP//UB7eJRtABW3I/LWiokezn6NJNLa8oz2zwwTcqEoqv+IymY/eycKHJM0HwsCHdXOmCVabvDK165uoX3Z5Zmr7tbBGqNTLfKTZO9/lnXa/zBL7Cy3rtR3C1aihi5uV9cIUxxK1nnUc7Xbs8gpcNRQEi8OfmzCG5taMHXPPw6EGqxBJl9Lgr1wbNZZfbi+Xfnc08wDHm9IrOnXkAO+y8mfdITlo+wO4i8lyxktl4vOcguQQzetfk8M2GM4AdtCt5tgISFGG48QkVWudnQYn3ug6dv7qb2JSo3vuh7fjrU2A1EeuQlPNySfQgJii67++29XhbrFTg6LI=
    # CWS Token
    - secure: A9sJWZ1SqgR6QzWdW/W8QsUyZVJd89Lgd8L+Cq3qIqSXqIg+PExAkvOq72H5Rug4dLwEZ9ApsGR3FpBV+QAQP72IR5voDAAYwBhsPbKe13T7v2u0sIGJW660PHP2ns5Ehkyj5MO0vPJM2owkuk55/5LsWEuSLwtnvd6Mts3jPUBqcHnorZqdhyn7qcWhqIULFhrXw1X3FFkjOHXItOGYWrFhCEoE8kl9/TgIo1sO81fxce3ARlAm992k/oSpaS/kJY1UK5DCTJChwTuaBw42mN6/ieFV5vP3LYhE54rX/zV+BMtfVP/nEoP2UbbzgrMaQ/1uyDL2VmOHkJNOFcpoBzrwnpQfw07W7/bi0hC8cr/AWiHXGGRTTg2TS+qe+ZWigmaM0DPqdX+uRPXHPU5pf+sKJzphujilxFiFY19Uh+6jU7cAeWdsRlJIiDW0h2hq3lh47sATjr/nwvD2fxe9JvnbV/MgFtnPGPB7yBtvcWUBzlQiHPAKy3pcvJ173H0UhvotWsL6foPrXAbgzTYW/rdjUg1dDHSIzHOJXawkPap2PIyVFGF9YFE1KGmhFps+ibKu+quPmzDZmNRi92UdsBi/EiUGe3VFGcW+8GuIvRb7Vw+EWick/Ox4isBOEB/WiW7vZN8wD+zLKlCm2o9/aiJbzXprl+qnU+GpoPGBinY=
    # CWS Secret
    - secure: AbOIyj31vzVtqGcUSawyqKALSU96ZCVe/vc/YAVtkLtnvku/TPMGoTScz3CBP16waCw+ed3nLTK9B4qYiQUgxgAJcxRf05j3w4dp+ZHOuilPY0F+5Q7a46zH8fyakfFveOUwAYfSrS/xvpXfhJ4cCozrEMEH6RZ6jrwp42YhfVi8lGAPsXyFLSHkxJ9HwOcZnDR05xIZiup2KD4ymTpHPxkyUF9EmMDDLp+ToYqjwq5ErJDzLOUV2dbpfXi/sJVDfjjF2O6YdrSetaOtxfQeKEf6hYpYotQCIYl86jYRbOCu3y6TNHi+G4+MZKjuCDRVeFrlPbZ746c6Y+pIA9UeUShCYOMGIWbEMzh+Zv/1GIKzkV9hq0oqx3PDWP7+VWSfnMsfMnvzXYiz8YPekqybLUILq6EJg+EkIHFkoc+nkB+9DAXNY5hyZ5p88Y3RUYSb3/U4EWDhDKzfrDjUtFTEPvCXgfRMmB+itim3YmH+eP0DN1b6+LitPa2YZIeyIh4mab+n4Aa+VGzHWFLrLVymqPxnHTrwouCUdjxo4uchYpfo1fm0nsIYtLVYsEmmsiXOnS5vOkLYRea+RF5AiHmVMi3DKcM8ArNu+wZ19pOhjtswE93HDWLpYjZTbTrQ2/mepSJg87FeLvYiH6CYDW/3UvE+0lRKlDvvCHQIz9ZL6KU=
    # AMO Secret
    - secure: giLAwO9LJ8Eip7GFDxK2BNWm2K1u+f+jCOeI2kvwhLWL5686JMeVs90ez+q617yokYEZW3XfdMZYfuGFD2c75Yj++5tUBRlaMn9euuccbsMytfR+O5MAoL9X8Nz57+jthMBgHFXBYrOe1nupaCfgG2kv8q+18MWJUIwxYCtVZEetQXNqRIwKH1GMu1cIO1vpq0fUYfuSsNO5Fjmgw/g+X5T8ASArpSbzzTvXI8yRkyqOfo+sn/LV6UmOirwhq9eVPZhdzzhI7AYIAh4Pr9Pmu+s0ck1nFfmL9j83nhMatdpKbA5ZUc4Bo1TOw1u+QJ0veN9aHYqnEJJVwR+OBJmqvmhRqqJWv60vSj/QNXH0b0swUh+SKt/aiG3kvwPGCHblsueUPdgKaeMrI0Wil8LFrtyFNlROi0X36xJZJpIncOVerK4mmd2DvB2+h0SGoGqM3cm+K1siPPBvreLimJ/AqYjKdmiI+z6bZXYA3m1/vsed8w1KF99sFuiTVwj+jd/jOBbTa602peIJQoIJivv90w/0XZWPsprmtJp1nrmiM0FURcy7M3//gZ7SkXvxkqO6cZSP62haXwA1pIDy+Z/XInQjWvxP9vuvATHh86FpUBhYemOtnVA+EIrJkekJntTVpyd15T2q0qFKdUYwTmZG7J+Z0nofw3B4bzbUxs/gtJM=
    # GitHub Token (for release)
    - secure: lTAEtc+R4/W3C/OcmXQ/EfdxS9/6c8NoKZ/CzzBbprJ9vKo1AyeSINsu3yryGViQgL87WXWIN1d+0P7ssJw3SLDhQvJUCzAdraRjOe2VzWW5z2HD18Mm1+lK5FYveV32bGcF4k0g8HvsXXUb654iEh8jpxa6AjQX7c75owrMjKkJMRwZSfHvrzBOKLzAHHNtRmU2if/KoOHTZyxAJwVY3UkKsr+ihO7uJZheUA64UWe/yNgQOy2Shq/fV7PfxggqAX0WzVUdWOF04uD/APdwnTR3X8Eqz0W1ux+AR2jFm/+8fjugzAUFElaSK2XQJQf6u3/0iHY0tLRY5XzH59XabaqOduy5YCOwT69ekZdQ/j2RmExEouNCJU9E9Rr+y8gZFR2hhVoLRWnGb0zNNw3UlBgAd8ER0d9mkHllfzuHFpJm3LXzSozNNdx89weXPZNDleu2Gs/R3kF3BsNssxh5AsrX9xFj5br5TjWdpFAlWcbD6Ti/MtBbJVgFXdc76oVP6H9HGouu3Rb+dOZkbyN9Bxsepn6kEt1xYnD5HwIlhte8/v+EiUcAzLg21R91MFZK1NbZwivexK+mm3rx4ezg8LlzQxM4fIeTdRf9+L4hXajBoVKgbmIgLGEmxcLCOLgSxSSSowT+Sk9LaX7e30Pn6Qqy9x79JQUmdLu7eeQOFsM=